name: squad
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ujson
  - numpy
  - pip
  - spacy=2.3.7
  - tensorboard
  - tensorflow
  - tensorboardX
  - tqdm
  - urllib3
  - pytorch
  - pip:
    - torch
